name: run unittest
on:
  pull_request:
    branches:
      - master
jobs:
  run-unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
      - run: yarn install
      - run: yarn jest
